[fix] driver autoscript_client & xt_client: stop polling thread on termination
Make sure that all components which have a polling thread stop it when
the component is terminated.
It's typically not a big deal as the threads would be ended
automatically when the whole process ends, or as soon as they attempts
to connect via the parent, which is gone. However, the errors can be
confusing.
This avoid such error in the log:
2026-02-23 09:57:05,589	ERROR	autoscript_client:1309:	Unexpected failure when polling settings
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odemis/driver/autoscript_client.py", line 1281, in _updateSettings
    beam_current = self.parent.get_beam_current(self.channel)
AttributeError: 'NoneType' object has no attribute 'get_beam_current'